version: '3'

services:
  educacao-gamificada:
    image: educacao-gamificada/educacaogamificada:latest
    ports:
      - "9090:9090"
    volumes:
      - ./dados:/educacaoGamificada/dados
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
